version: "3.8"

services:
    backend:
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --workers 4
        stdin_open: true
        tty: true
        ports:
          - 8000:8000
        volumes:
            - ./backend:/backend
