version: "3.8"

services:
  users_db:
    image: postgres:13.4
    env_file: ./backend/users/config/.env
    volumes:
      - users_data:/var/lib/postgresql/data
      - ./backend/users/docker/postgres:/docker-entrypoint-initdb.d
    container_name: floppshop_users_db
    restart: always

  rabbitmq:
    image: bitnami/rabbitmq:3.9
    ports:
      - 15672:15672
    volumes:
      - rabbitmqdata:/bitnami
    container_name: floppshop_rabbitmq

  users:
    build:
      context: ./backend/users
      dockerfile: docker/python/Dockerfile
    env_file: ./backend/users/config/.env
    container_name: floppshop_users
    restart: always
    depends_on:
      - users_db
      - rabbitmq
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload --workers 4
    stdin_open: true
    tty: true
    ports:
      - 8001:8001
    volumes:
      - ./backend/users/:/app

volumes:
  users_data:
  rabbitmqdata: